### ISSUE TITLE
Execute Graph_Algo,

### ISSUE THREAD

**Issue by elonezra** [dean985/mazewaze#2]
- [ ] public boolean isConnected();

- [ ] public List<node_data> TSP(List<Integer> targets);
- [x] public graph copy();

It represents a collection of algorithms on directed and weighted graph.

operation on graph

**Comment by elonezra** [comment]
**ToDo**

- [ ] public void init(graph g);
`	 * Init this set of algorithms on the parameter - graph.
`

- [ ] public graph copy();
`	 * Compute a deep copy of this graph.`

- [ ] public void init(String file_name);
`	 * Init a graph from file
`


- [ ] public void save(String file_name);
`Saves the graph to a file.`

- [ ] public boolean isConnected();
`* Returns true if and only if (iff) there is a valid path from EVREY node to each
 * other node. NOTE: assume directional graph - a valid path (a-->b) does NOT imply a valid path (b-->a).
`

- [ ] public double shortestPathDist(int src, int dest);
`returns the length of the shortest path between src to dest
`

- [ ] public List<node_data> shortestPath(int src, int dest);
`returns the the shortest path between src to dest - as an ordered List of nodes:
	 * src--> n1-->n2-->...dest
	 * see: https://en.wikipedia.org/wiki/Shortest_path_problem
	 * @param src - start node
	 * @param dest - end (target) node`

- [ ] public List<node_data> TSP(List<Integer> targets);

`	 * computes a relatively short path which visit each node in the targets List.\n
	 * Note: this is NOT the classical traveling salesman problem, 
	 * as you can visit a node more than once, and there is no need to return to source node - 
	 * just a simple path going over all nodes in the list. 
	 * @param targets`
